"""

Make migration script for generating migration files.

This script is used to generate migration files for the database.

This file is subject to the terms and conditions defined in file 'LICENSE',
which is part of this source code package.
"""

from alembic import command
from alembic.config import Config as AlembicConfig
from alembic.util import AutogenerateDiffsDetected

from fastapi__template.app import create_app

# init app
app = create_app()
app.dependency_overrides = {}


def main():
    """Generate migration files."""
    alembic_cfg = AlembicConfig("fastapi__template/migrations/alembic.ini")

    try:
        command.check(alembic_cfg)
    except AutogenerateDiffsDetected:
        command.revision(alembic_cfg, autogenerate=True)
